-- function ReloadConfig()
--   for name,_ in pairs(package.loaded) do
--     if name:match("^myconfig") then
--       package.loaded[name] = nil
--     end
--   end
--   dofile(vim.env.MYVIMRC)
-- end
